services:
  # --- BASE DE DONNÉES (Infrastructure) ---
  postgres:
    image: postgres:16
    container_name: eco_agri_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eco_network

  # --- INITIALISATION D'AIRFLOW (Run Once) ---
  airflow-init:
    build:
      context: .
      dockerfile: data_processing/Dockerfile.airflow
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "
        sleep 5 &&
        airflow db init &&
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin || true
      "
    networks:
      - eco_network

  # --- MICROSERVICE 1 : DATA FACTORY (Airflow + Spark) ---
  airflow:
    build:
      context: .
      dockerfile: data_processing/Dockerfile.airflow
    container_name: airflow_spark_service
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PYTHONPATH: /opt/airflow
      AIRFLOW__WEBSERVER__WORKERS: 1
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: 300
      AIRFLOW_CONN_SPARK_DEFAULT: 'spark://local?master=local[*]'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
    volumes:
      - ./data_processing/airflow/dags:/opt/airflow/dags
      - ./data_processing/airflow/tasks:/opt/airflow/tasks
      - ./data:/opt/airflow/data 
      - ./logs/airflow:/opt/airflow/logs
    ports:
      - "8081:8080"
    command: >
       bash -c "airflow webserver --port 8080 --workers 1"
    networks:
      - eco_network
  airflow-scheduler:
    build:
      context: .
      dockerfile: data_processing/Dockerfile.airflow
    container_name: airflow_scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env 
    environment:
      PYTHONPATH: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_CONN_SPARK_DEFAULT: 'spark://local?master=local[*]'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
    volumes:
      - ./data_processing/airflow/dags:/opt/airflow/dags
      - ./data_processing/airflow/tasks:/opt/airflow/tasks
      - ./data:/opt/airflow/data # Volume Medallion
      - ./logs/airflow:/opt/airflow/logs
    command: scheduler
    networks:
      - eco_network
  # --- MICROSERVICE 2 : API & INFERENCE (FastAPI) ---
  api-service:
    build:
      context: .
      dockerfile: src/Dockerfile.api
    image: eco-agri-backend-api
    container_name: backend_api
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./artifacts:/app/artifacts
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./.env:/app/.env
      - ./mlruns:/app/mlruns
    ports:
      - "8000:8000"
    networks:
      - eco_network

  # --- MICROSERVICE 3 : MLFLOW (Mlobs / Tracking) ---
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - GIT_PYTHON_REFRESH=quiet
      - MLFLOW_HTTP_WHITELISTED_HOSTS=localhost,127.0.0.1,mlflow,mlflow:5000,backend_api
      
    volumes:
      - ./mlruns:/app/mlruns
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri sqlite:///mlflow.db 
      --default-artifact-root /app/mlruns
      --allowed-hosts "*"
    networks:
      - eco_network
  

  # --- FRONTEND : Next.js App ---
  frontend:
    build:
      context: ../Projet-Eco-Agronomist-IA-Frontend/app-ergonomie
      dockerfile: Dockerfile
    image: eco-agri-frontend
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api-service
    volumes:
      - ../Projet-Eco-Agronomist-IA-Frontend/app-ergonomie:/app
      - /app/node_modules
      - /app/.next
    networks:
      - eco_network


networks:
  eco_network:
    driver: bridge

volumes:
  postgres_data:
