FROM apache/airflow:2.7.1-python3.10

USER root


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-11-jdk \
    ant \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*


USER airflow


COPY data-processing/requirements-spark.txt .
RUN pip install --no-cache-dir -r requirements-spark.txt

# (Créer les dossiers pour l'architecture Medallion à l'intérieur du conteneur
RUN mkdir -p /opt/airflow/data/bronze /opt/airflow/data/silver /opt/airflow/data/gold