FROM apache/airflow:2.7.1-python3.10

USER root


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-11-jdk \
    procps \
    ant \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/


COPY data-processing/requirements-spark.txt .

RUN uv pip install --no-cache --system \
    "apache-airflow-providers-apache-spark" \
    -r requirements-spark.txt \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.1/constraints-3.10.txt"

# (Créer les dossiers pour l'architecture Medallion à l'intérieur du conteneur
RUN mkdir -p /opt/airflow/data/bronze /opt/airflow/data/silver /opt/airflow/data/gold


USER airflow
