FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV PYTHONPATH=/app

RUN uv pip install --no-cache --system \
    --extra-index-url https://download.pytorch.org/whl/cpu \
    torch torchvision ultralytics

COPY src/requirements.txt .
RUN uv pip install --no-cache --system -r requirements.txt

COPY src/ /app/src/
COPY artifacts/ /app/artifacts/


CMD ["sh", "-c", "sleep 5 && uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"] 